replicaCount: 1

image:
  repository: assignmentdevops/chat-app
  tag: v1.0
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

secretName: dockerhub-secret

service:
  port: 8080

url: chat.exmaple.com
