apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ include "chart.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
